/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillTreeRouteImport } from './routes/_authenticated/skill-tree'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated/play.index'
import { Route as AuthenticatedPlayMapIdRouteImport } from './routes/_authenticated/play.$mapId'

const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillTreeRoute = AuthenticatedSkillTreeRouteImport.update({
  id: '/skill-tree',
  path: '/skill-tree',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPlayRoute,
} as any)
const AuthenticatedPlayMapIdRoute = AuthenticatedPlayMapIdRouteImport.update({
  id: '/$mapId',
  path: '/$mapId',
  getParentRoute: () => AuthenticatedPlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/codex': typeof CodexRoute
  '/play': typeof AuthenticatedPlayRouteWithChildren
  '/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/play/$mapId': typeof AuthenticatedPlayMapIdRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/codex': typeof CodexRoute
  '/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/play/$mapId': typeof AuthenticatedPlayMapIdRoute
  '/play': typeof AuthenticatedPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/codex': typeof CodexRoute
  '/_authenticated/play': typeof AuthenticatedPlayRouteWithChildren
  '/_authenticated/skill-tree': typeof AuthenticatedSkillTreeRoute
  '/_authenticated/play/$mapId': typeof AuthenticatedPlayMapIdRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/codex'
    | '/play'
    | '/skill-tree'
    | '/play/$mapId'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/codex' | '/skill-tree' | '/play/$mapId' | '/play'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/codex'
    | '/_authenticated/play'
    | '/_authenticated/skill-tree'
    | '/_authenticated/play/$mapId'
    | '/_authenticated/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CodexRoute: typeof CodexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skill-tree': {
      id: '/_authenticated/skill-tree'
      path: '/skill-tree'
      fullPath: '/skill-tree'
      preLoaderRoute: typeof AuthenticatedSkillTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedPlayRoute
    }
    '/_authenticated/play/$mapId': {
      id: '/_authenticated/play/$mapId'
      path: '/$mapId'
      fullPath: '/play/$mapId'
      preLoaderRoute: typeof AuthenticatedPlayMapIdRouteImport
      parentRoute: typeof AuthenticatedPlayRoute
    }
  }
}

interface AuthenticatedPlayRouteChildren {
  AuthenticatedPlayMapIdRoute: typeof AuthenticatedPlayMapIdRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
}

const AuthenticatedPlayRouteChildren: AuthenticatedPlayRouteChildren = {
  AuthenticatedPlayMapIdRoute: AuthenticatedPlayMapIdRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
}

const AuthenticatedPlayRouteWithChildren =
  AuthenticatedPlayRoute._addFileChildren(AuthenticatedPlayRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRouteWithChildren
  AuthenticatedSkillTreeRoute: typeof AuthenticatedSkillTreeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPlayRoute: AuthenticatedPlayRouteWithChildren,
  AuthenticatedSkillTreeRoute: AuthenticatedSkillTreeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CodexRoute: CodexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
